/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RezerwacjaRouteImport } from './routes/rezerwacja'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KalkulatorDmcRouteImport } from './routes/kalkulator-dmc'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWinietyRouteImport } from './routes/admin.winiety'
import { Route as AdminWiadomosciRouteImport } from './routes/admin.wiadomosci'
import { Route as AdminUstawieniaRouteImport } from './routes/admin.ustawienia'
import { Route as AdminTresciRouteImport } from './routes/admin.tresci'
import { Route as AdminRezerwacjeRouteImport } from './routes/admin.rezerwacje'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKalendarzRouteImport } from './routes/admin.kalendarz'
import { Route as AdminBlokadyRouteImport } from './routes/admin.blokady'
import { Route as ApiPublicReservationNotifyRouteImport } from './routes/api/public/reservation-notify'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const RezerwacjaRoute = RezerwacjaRouteImport.update({
  id: '/rezerwacja',
  path: '/rezerwacja',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorDmcRoute = KalkulatorDmcRouteImport.update({
  id: '/kalkulator-dmc',
  path: '/kalkulator-dmc',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWinietyRoute = AdminWinietyRouteImport.update({
  id: '/winiety',
  path: '/winiety',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWiadomosciRoute = AdminWiadomosciRouteImport.update({
  id: '/wiadomosci',
  path: '/wiadomosci',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUstawieniaRoute = AdminUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTresciRoute = AdminTresciRouteImport.update({
  id: '/tresci',
  path: '/tresci',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRezerwacjeRoute = AdminRezerwacjeRouteImport.update({
  id: '/rezerwacje',
  path: '/rezerwacje',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKalendarzRoute = AdminKalendarzRouteImport.update({
  id: '/kalendarz',
  path: '/kalendarz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlokadyRoute = AdminBlokadyRouteImport.update({
  id: '/blokady',
  path: '/blokady',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicReservationNotifyRoute =
  ApiPublicReservationNotifyRouteImport.update({
    id: '/api/public/reservation-notify',
    path: '/api/public/reservation-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cennik': typeof CennikRoute
  '/faq': typeof FaqRoute
  '/kalkulator-dmc': typeof KalkulatorDmcRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/admin/blokady': typeof AdminBlokadyRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rezerwacje': typeof AdminRezerwacjeRoute
  '/admin/tresci': typeof AdminTresciRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wiadomosci': typeof AdminWiadomosciRoute
  '/admin/winiety': typeof AdminWinietyRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/reservation-notify': typeof ApiPublicReservationNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/faq': typeof FaqRoute
  '/kalkulator-dmc': typeof KalkulatorDmcRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/admin/blokady': typeof AdminBlokadyRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rezerwacje': typeof AdminRezerwacjeRoute
  '/admin/tresci': typeof AdminTresciRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wiadomosci': typeof AdminWiadomosciRoute
  '/admin/winiety': typeof AdminWinietyRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/reservation-notify': typeof ApiPublicReservationNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cennik': typeof CennikRoute
  '/faq': typeof FaqRoute
  '/kalkulator-dmc': typeof KalkulatorDmcRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/admin/blokady': typeof AdminBlokadyRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rezerwacje': typeof AdminRezerwacjeRoute
  '/admin/tresci': typeof AdminTresciRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wiadomosci': typeof AdminWiadomosciRoute
  '/admin/winiety': typeof AdminWinietyRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/reservation-notify': typeof ApiPublicReservationNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cennik'
    | '/faq'
    | '/kalkulator-dmc'
    | '/kontakt'
    | '/login'
    | '/oferta'
    | '/rezerwacja'
    | '/admin/blokady'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/rezerwacje'
    | '/admin/tresci'
    | '/admin/ustawienia'
    | '/admin/wiadomosci'
    | '/admin/winiety'
    | '/admin/'
    | '/api/public/contact'
    | '/api/public/reservation-notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cennik'
    | '/faq'
    | '/kalkulator-dmc'
    | '/kontakt'
    | '/login'
    | '/oferta'
    | '/rezerwacja'
    | '/admin/blokady'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/rezerwacje'
    | '/admin/tresci'
    | '/admin/ustawienia'
    | '/admin/wiadomosci'
    | '/admin/winiety'
    | '/admin'
    | '/api/public/contact'
    | '/api/public/reservation-notify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cennik'
    | '/faq'
    | '/kalkulator-dmc'
    | '/kontakt'
    | '/login'
    | '/oferta'
    | '/rezerwacja'
    | '/admin/blokady'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/rezerwacje'
    | '/admin/tresci'
    | '/admin/ustawienia'
    | '/admin/wiadomosci'
    | '/admin/winiety'
    | '/admin/'
    | '/api/public/contact'
    | '/api/public/reservation-notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CennikRoute: typeof CennikRoute
  FaqRoute: typeof FaqRoute
  KalkulatorDmcRoute: typeof KalkulatorDmcRoute
  KontaktRoute: typeof KontaktRoute
  LoginRoute: typeof LoginRoute
  OfertaRoute: typeof OfertaRoute
  RezerwacjaRoute: typeof RezerwacjaRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicReservationNotifyRoute: typeof ApiPublicReservationNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rezerwacja': {
      id: '/rezerwacja'
      path: '/rezerwacja'
      fullPath: '/rezerwacja'
      preLoaderRoute: typeof RezerwacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulator-dmc': {
      id: '/kalkulator-dmc'
      path: '/kalkulator-dmc'
      fullPath: '/kalkulator-dmc'
      preLoaderRoute: typeof KalkulatorDmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/winiety': {
      id: '/admin/winiety'
      path: '/winiety'
      fullPath: '/admin/winiety'
      preLoaderRoute: typeof AdminWinietyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wiadomosci': {
      id: '/admin/wiadomosci'
      path: '/wiadomosci'
      fullPath: '/admin/wiadomosci'
      preLoaderRoute: typeof AdminWiadomosciRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ustawienia': {
      id: '/admin/ustawienia'
      path: '/ustawienia'
      fullPath: '/admin/ustawienia'
      preLoaderRoute: typeof AdminUstawieniaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tresci': {
      id: '/admin/tresci'
      path: '/tresci'
      fullPath: '/admin/tresci'
      preLoaderRoute: typeof AdminTresciRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rezerwacje': {
      id: '/admin/rezerwacje'
      path: '/rezerwacje'
      fullPath: '/admin/rezerwacje'
      preLoaderRoute: typeof AdminRezerwacjeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kalendarz': {
      id: '/admin/kalendarz'
      path: '/kalendarz'
      fullPath: '/admin/kalendarz'
      preLoaderRoute: typeof AdminKalendarzRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blokady': {
      id: '/admin/blokady'
      path: '/blokady'
      fullPath: '/admin/blokady'
      preLoaderRoute: typeof AdminBlokadyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/reservation-notify': {
      id: '/api/public/reservation-notify'
      path: '/api/public/reservation-notify'
      fullPath: '/api/public/reservation-notify'
      preLoaderRoute: typeof ApiPublicReservationNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlokadyRoute: typeof AdminBlokadyRoute
  AdminKalendarzRoute: typeof AdminKalendarzRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRezerwacjeRoute: typeof AdminRezerwacjeRoute
  AdminTresciRoute: typeof AdminTresciRoute
  AdminUstawieniaRoute: typeof AdminUstawieniaRoute
  AdminWiadomosciRoute: typeof AdminWiadomosciRoute
  AdminWinietyRoute: typeof AdminWinietyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlokadyRoute: AdminBlokadyRoute,
  AdminKalendarzRoute: AdminKalendarzRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRezerwacjeRoute: AdminRezerwacjeRoute,
  AdminTresciRoute: AdminTresciRoute,
  AdminUstawieniaRoute: AdminUstawieniaRoute,
  AdminWiadomosciRoute: AdminWiadomosciRoute,
  AdminWinietyRoute: AdminWinietyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CennikRoute: CennikRoute,
  FaqRoute: FaqRoute,
  KalkulatorDmcRoute: KalkulatorDmcRoute,
  KontaktRoute: KontaktRoute,
  LoginRoute: LoginRoute,
  OfertaRoute: OfertaRoute,
  RezerwacjaRoute: RezerwacjaRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicReservationNotifyRoute: ApiPublicReservationNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
